version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7.2
      nodejs : 12.18.2
    pre_build:
    commands:
      - pip install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - npm install
      - npm install serverless
  build:
    commands:
      - sls deploy
artifacts:
  files:
    - '**/*'
  base-directory: .serverless